articles/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = 'articles'
urlpatterns = [
    path('', TemplateView.as_view(
        template_name='articles/index.html'), name='index'),
    path('register/', views.Register.as_view(), name='register'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('publish/', views.PublishArticle.as_view(), name='publish-article'),
    path('personal/', views.personal_page, name='personal-page'),
    path('personal/<int:article_id>/',
         views.personal_article, name='personal-article'),
    path('personal/<int:article_id>/delete/',
         views.delete_article, name='delete-article'),
    path('personal/<int:article_id>/comment/',
         views.author_comment, name='author-comment'),
    path('personal/<int:article_id>/update/',
         views.update_article, name='update-article'),
    path('public/', views.public_page, name='public'),
    path('public/<int:article_id>/', views.public_article, name='public-article'),
    path('public/<int:article_id>/comment/',
         views.leave_comment, name='leave-comment'),
    path('become_user/', TemplateView.as_view(template_name='articles/become_user.html'),
         name='become-user'),
    path('public/<int:article_id>/like/', views.leave_like, name='like'),
    path('public/<int:article_id>/dislike/',
         views.leave_dislike, name='dislike'),
    path('public/tags/trending/', views.trending_tags, name='trending-tags'),
    path('public/tags/<str:tag>/', views.articles_through_tag, name='articles-tag'),
    path('public/search-article/', views.search_article,
         name='search-article'),
    path('public/articles/trending/',
         views.trending_articles, name='trending-articles'),
    path('public/authors/<str:author>/',
         views.author_page, name='articles-author'),
    path('public/authors/<str:author>/subscribe/',
         views.subscribe, name='subscribe')
]

ligma/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('', include('articles.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class Article(models.Model):
    title = models.CharField(max_length=255, null=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(null=False)
    pub_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='store/images/', null=False)
    tags = TaggableManager()

    def __str__(self):
        return self.title


class Comment(models.Model):
    commentator = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE)
    content = models.TextField(null=False)
    pub_date = models.DateTimeField(auto_now_add=True)


class Reaction(models.Model):
    """ 
    if value == 1, this means user liked an article;
    if value == -1, this means user disliked an article;
    """
    value = models.SmallIntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)


class ArticleReading(models.Model):
    """
    Model for tracking how many times an article was read
    """
    times_read = models.PositiveBigIntegerField(default=0)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-times_read']


class Channel(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)


class Subscription(models.Model):
    subscriber = models.ForeignKey(User, on_delete=models.CASCADE)
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE)

articles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Article, Comment


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class PublishArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        exclude = ['author', 'pub_date']


class LeaveCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['commentator', 'article', 'pub_date']


class SearchForm(forms.Form):
    search_string = forms.CharField(max_length=255)

articles/views.py
from datetime import timedelta
from django.views import View
from django.utils import timezone
from django.db.models import Q
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.core.paginator import Paginator
from taggit.models import Tag
from .forms import NewUserForm, PublishArticleForm, LeaveCommentForm, SearchForm
from .models import Article, Comment, Reaction, ArticleReading, Channel, Subscription


class Register(View):
    form_class = NewUserForm
    template_name = 'articles/registration.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            # Create a channel entity while creating new users
            # this avoids excessive queries and if conditions
            # in another views when dealing with subscription
            channel = Channel(owner=user)
            channel.save()
            login(request, user)
            username = form.cleaned_data['username']
            messages.info(request, f'Welcome to the Ligma, {username}')
            return redirect('articles:index')

        return render(request, self.template_name, {'form': form})


class Login(View):
    form_class = AuthenticationForm
    template_name = 'articles/login.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                messages.info(request, f"Welcome back to Ligma, {username}")
                return redirect('articles:index')
        return render(request, self.template_name, {'form': form})


def logout_request(request):
    logout(request)
    messages.info(request, "You have successfully logged out.")
    return redirect('articles:index')


class PublishArticle(View):
    form_class = PublishArticleForm
    template_name = 'articles/publish_article.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            form.instance.author = request.user
            obj.save()
            form.save_m2m()
            messages.info(
                request, 'You successfully published new article')
            return HttpResponseRedirect(reverse('articles:personal-page'))
        return render(request, 'articles/publish_article.html', {'form': form})

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


@login_required()
def update_article(request, article_id):
    current_user = request.user
    article = Article.objects.filter(id=article_id).first()
    if not article:
        return render(request, 'articles/not_exists.html')
    else:
        if article.author_id != current_user.id:
            return render(request, 'articles/not_yours.html')
        if request.method == 'POST':
            form = PublishArticleForm(
                request.POST, request.FILES, instance=article)
            if form.is_valid():
                obj = form.save(commit=False)
                form.instance.author = request.user
                obj.save()
                form.save_m2m()
                messages.info(
                    request, 'You successfully updated this article')
                return HttpResponseRedirect(reverse('articles:personal-article', args=(article_id, )))
        else:
            form = PublishArticleForm(instance=article)
            return render(request, 'articles/update_article.html', {'form': form, 'article_id': article_id})


def public_page(request):
    articles_list = Article.objects.select_related('author').\
        prefetch_related('tags').order_by('-pub_date').all()
    paginator = Paginator(articles_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'articles/public_page.html', {'page_obj': page_obj})


@login_required()
def personal_page(request):
    current_user = request.user
    articles_list = Article.objects.filter(author_id=current_user.id).\
        prefetch_related('tags').order_by('-pub_date')
    total_readings = 0
    for article in articles_list:
        article_times_read = article.articlereading_set.all()
        if len(article_times_read) < 1:
            continue
        else:
            total_readings += article_times_read[0].times_read
    paginator = Paginator(articles_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'articles/personal_page.html', {'page_obj': page_obj,
                                                           'total_readings': total_readings})


@login_required()
def personal_article(request, article_id):
    current_user = request.user
    article = Article.objects.filter(
        id=article_id).first()
    if not article:
        return render(request, 'articles/not_exists.html')
    else:
        if article.author_id != current_user.id:
            return render(request, 'articles/not_yours.html')
        likes = Reaction.objects.filter(
            article=article).filter(value=1).count()
        dislikes = Reaction.objects.filter(
            article=article).filter(value=-1).count()
        article_read = ArticleReading.objects.filter(article=article).first()
        times_read = 0
        if article_read:
            times_read = article_read.times_read
        message_to_user = 0
        reaction = Reaction.objects.filter(
            Q(article=article) & Q(author=current_user)).first()
        if reaction:
            if reaction.value == -1:
                message_to_user = "You disliked your article"
            elif reaction.value == 1:
                message_to_user = "You liked your article"
        return render(request, 'articles/personal_article.html', {'article': article,
                                                                  'likes': likes,
                                                                  'dislikes': dislikes,
                                                                  'message_to_user': message_to_user,
                                                                  'times_read': times_read})


def public_article(request, article_id):
    current_user = request.user
    article = Article.objects.select_related('author').\
        filter(id=article_id).first()

    if not article:
        return render(request, 'articles/not_exists.html')
    else:
        # comments = Comment.objects.select_related('commentator').filter(
        #     article=article).order_by('-pub_date').all()
        likes = Reaction.objects.filter(
            article=article).filter(value=1).count()
        dislikes = Reaction.objects.filter(
            article=article).filter(value=-1).count()
        message_to_user = None
        article_read = ArticleReading.objects.filter(article=article).first()
        times_read = 0
        subscription_status = 'You are not subscribed to this author'
        channel = Channel.objects.filter(owner=article.author).first()
        subscription = Subscription.objects.filter(
            Q(subscriber=current_user) &
            Q(channel=channel)
        ).first()
        if subscription:
            subscription_status = 'You are subscribed to this author'
        if article.author == current_user:
            subscription_status = 'This article belongs to you'
        if not article_read:
            if current_user.is_authenticated:
                article_read = ArticleReading(times_read=1, article=article)
                article_read.save()
                times_read = article_read.times_read
        else:
            if current_user.is_authenticated:
                article_read.times_read += 1
                article_read.save()
            times_read = article_read.times_read
        if current_user.is_authenticated:
            reaction = Reaction.objects.filter(
                Q(article=article) & Q(author=current_user)).first()
            if reaction:
                if reaction.value == -1:
                    message_to_user = "You disliked this article"
                elif reaction.value == 1:
                    message_to_user = "You liked this article"
        return render(request, 'articles/public_article.html', {'article': article,
                                                                # 'comments': comments,
                                                                'likes': likes,
                                                                'dislikes': dislikes,
                                                                'message_to_user': message_to_user,
                                                                'times_read': times_read,
                                                                'subscription_status': subscription_status
                                                                })

articles/templates/articles/author_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>Author page</title>
</head>
<body>
    {% load crispy_forms_tags %}
    <div class="container py-5">
        {% if messages %}
            {% for message in messages %}
                <strong>{{ message }}</strong>
            {% endfor %}
        {% endif %}
        {% if not subscription_status %}
            <h1>This public page is about your articles</h1>
            <h2>If you want to visit your personal page, follow this link</h2>
            <a href="{% url 'articles:personal-page'%}">Your personal page</a>
        {% else %}
            <h1>This page belongs to the author <strong>{{author}}</strong></h1>
            <form action="{% url 'articles:subscribe' author %}">
                {% csrf_token %}
                <button class="btn btn-primary" type="submit">{{ subscription_status }}</button>
            </form>
        {% endif %}
    <h2>{{ author }} totally published {{ articles_number }} articles</h2>
    <h2>{{ author }}'s articles were totally read {{ total_readings }} times</h2>
    <h2>---Articles---</h2>
    {% for article in articles %}
        <h2>Title: {{ article.title }}</h2>
        {% if article.image %}
          <img src="{{ article.image.url }}" alt="Article image" style="width: 10%; float: right; margin-right: 10px;">
        {% endif %}
        <p>Author: <a href="{% url 'articles:articles-author' article.author %}">{{ article.author }}</a></p>
        {% for tag in article.tags.all %}
          <a href="{% url 'articles:articles-tag' tag %}">#{{ tag }}</a>
        {% endfor %}
        <p>Publication date: {{ article.pub_date.date }}</p>
        <form action="{% url 'articles:public-article' article.id %}">
          {% csrf_token %}
          <button class="btn btn-primary" type="submit">Read</button>
        </form>
      {% endfor %}
    </div>
</body>
</html>

articles/templates/articles/become_user.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>Become User</title>
  </head>
  <body>
    {% load crispy_forms_tags %}
    <div class="container py-5">
      <p class="text-center" style="font-size: 500">
        Please,
        <a href="{% url 'articles:register' %}">Register</a><br />
        OR <br />
        <a href="{% url 'articles:login' %}">Login</a>.
      </p>
    </div>
  </body>
</html>

articles/templates/articles/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>LIGMA Homepage</title>
  </head>
  <body>
    {% load crispy_forms_tags %}
    <div class="container py-5">
      <h1>Welcome to the LIGMA</h1>
      {% if user.is_authenticated %}
        <p>You are authenticated as <strong>{{ user }}</strong></p>
      {% endif %}
      <p>
        LIGMA is a Website for publication, reading and discussing articles
        about anything you want
      </p>
      <a href="{% url 'articles:public' %}">See articles published by our users</a> <br>
      <a href="{% url 'articles:trending-articles' %}">See trending articles</a> <br>
      <a href="{% url 'articles:trending-tags' %}">See most popular tags on LIGMA for the last time</a> <br>
      <a href="{% url 'articles:search-article' %}">Search for a particular article</a>
      <br />
      {% if messages %} 
        {% for message in messages%} 
          <strong>{{ message }}</strong> 
        {% endfor %}
      {% endif %}
      <br />
      {% if user.is_authenticated %}
        <a href="{% url 'articles:publish-article' %}">Publish new article here</a>
        <br />
        <a href="{% url 'articles:personal-page'%}">You personal page</a>
        <br />
        <a href="{% url 'articles:logout' %}">Log Out</a>
      {% else %}
        <p>In order to publish your own articles you need to be an authenticated
        user</p>
        <a href="{% url 'articles:register' %}">Register</a><br />
        <a href="{% url 'articles:login' %}">Log In</a><br />
      {% endif %}
    </div>
  </body>
</html>

articles/templates/articles/personal_article.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>Your article</title>
  </head>
  <body>
    {% load crispy_forms_tags %}
    <div class="container py-5">
      {% if messages %} 
        {% for message in messages %} 
          {{ message }} 
        {% endfor %}
      {% endif %}
      <h2>Title: {{ article.title }}</h2>
      <img src="{{ article.image.url }}" alt="Article image" style="width: 10%; float: right; margin-right: 10px;">
      <h3>Content:</h3>
      <p>{{ article.content }}</p>
      {% for tag in article.tags.all %}
        <a href="{% url 'articles:articles-tag' tag %}">#{{ tag }}</a>
      {% endfor %}
      <p>Publication date: {{ article.pub_date.date }}</p>
      <a href="{% url 'articles:update-article' article.id %}">Edit your article</a>
      <p>Click this button if you want to delete this article:</p>
      <form action="{% url 'articles:delete-article' article.id %}">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit">Delete article</button>
      </form>
      <p>This article was read {{ times_read }} times</p>
      <h3>Readers reactions</h3>
      {% if message_to_user %}
        <p>{{message_to_user}}</p>
      {% endif %}
      <p>{{ likes }} likes | {{ dislikes }} dislikes</p>
      <h3>Comment section</h3>
      <a href="{% url 'articles:author-comment' article.id %}">Comment your article here</a>

      {% if article.comment_set.count > 0 %} 
        {% for comment in article.comment_set.all|dictsortreversed:"pub_date" %}
          <div class="container py-5">
            <p>Comment: {{ comment.content }}</p>
            <p>Left by {{ comment.commentator }} {{ comment.pub_date.date }}</p>
          </div>
        {% endfor %} 
      {% else %}
        <p>No comments left yet</p>
      {% endif %}
    </div>
  </body>
</html>

articles/templates/articles/personal_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>Your personal page</title>
  </head>
  <body>
    {% load crispy_forms_tags %} 
    {% if page_obj %}
    <div class="container py-5">
      <a href="{% url 'articles:index' %}">To the homepage</a>
      {% if messages %} 
        {% for message in messages %}
          <p>{{ message }}</p>
        {% endfor %} 
      {% endif %}
      <h1>Your Published articles</h1>
      <h2>Totally your articles were read {{ total_readings }} times</h2>
      <a href="{% url 'articles:publish-article' %}">Publish new article here</a>
      {% for article in page_obj %}
        <h2>Title: {{ article.title }}</h2>
        <img src="{{ article.image.url }}" alt="Article image" style="width: 10%; float: right; margin-right: 10px;">
        {% for tag in article.tags.all %}
          <a href="{% url 'articles:articles-tag' tag %}">#{{ tag }}</a>
        {% endfor %}
        <p>Publication date: {{ article.pub_date.date }}</p>
        <a href="{% url 'articles:personal-article' article.id %}">More about this article</a>
        <p>Click this button if you want to delete this article:</p>
        <form action="{% url 'articles:delete-article' article.id %}">
          {% csrf_token %}
          <button class="btn btn-primary" type="submit">Delete article</button>
        </form>
      {% endfor %}
    </div>
    <div class="pagination" class="container py-5">
      <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
    {% else %}
    <div class="container py-5">
      <a href="{% url 'articles:index' %}">To the homepage</a>
      {% if messages %} 
        {% for message in messages %}
          <strong>{{ message }}</strong>
        {% endfor %} 
      {% endif %}
      <h2>Looks like you haven't published anything yet</h2>
    </div>
    {% endif %}
  </body>
</html>

articles/templates/articles/public_article.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>Article</title>
  </head>
  <body>
    {% load crispy_forms_tags %}
    <div class="container py-5">
      <p>{{ subscription_status }}</p>
      <h2>Title: {{ article.title }}</h2>
      <img src="{{ article.image.url }}" alt="Article image" style="width: 10%; float: right; margin-right: 10px;">
      <p>Author: <a href="{% url 'articles:articles-author' article.author %}">{{ article.author }}</a></p>
      <p>Content:</p>
      <p>{{ article.content }}</p>
      {% for tag in article.tags.all %}
        <a href="{% url 'articles:articles-tag' tag %}">#{{ tag }}</a>
      {% endfor %}
      <p>Publication date: {{ article.pub_date.date }}</p>
      <p>This article was read {{ times_read }} times</p>
      <h3>Readers reactions</h3>
      {% if message_to_user %}
        <p>{{message_to_user}}</p>
      {% endif %}
      {% if user.is_authenticated %}
        <form action="{% url 'articles:like' article.id %}">
          {% csrf_token %}
          <button class="btn btn-primary" type="submit">Like</button>
        </form>
        <form action="{% url 'articles:dislike' article.id %}">
          {% csrf_token %}
          <button class="btn btn-primary" type="submit">Dislike</button>
        </form>
      {% else %}
        <a href="{% url 'articles:become-user' %}">Become an authenticated user if you want to leave a reaction</a>
      {% endif %}
      <p>{{ likes }} likes | {{ dislikes }} dislikes</p>
      <h3>Comment section</h3>
      {% if user.is_authenticated %}
        <a href="{% url 'articles:leave-comment' article.id %}">You can leave your comment here</a>
      {% else %}
        <a href="{% url 'articles:become-user' %}">Become an authenticated user if you want to leave a comment</a>
      {% endif %} 
      {% if article.comment_set.count > 0 %} 
        {% for comment in article.comment_set.all|dictsortreversed:"pub_date" %}
          <div class="container py-5">
            <p>Comment: {{ comment.content }}</p>
            <p>Left by {{ comment.commentator }} {{ comment.pub_date.date }}</p>
          </div>
        {% endfor %} 
      {% else %}
        <p>No comments left yet</p>
      {% endif %}
    </div>
  </body>
</html>

articles/templates/articles/public_page.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>LIGMA Articles</title>
  </head>
  <body>
    {% load crispy_forms_tags %}
    <div class="container py-5">
      <h1>LIGMA Articles</h1>
      <a href="{% url 'articles:index' %}">To the homepage</a><br>
      <a href="{% url 'articles:search-article' %}">Search for a particular article</a>
      {% if message_to_user %}
        <h2>{{ message_to_user }}</h2>
      {% endif %}
      {% for article in page_obj %}
        <h2>Title: {{ article.title }}</h2>
        {% if article.image %}
          <img src="{{ article.image.url }}" alt="Article image" style="width: 10%; float: right; margin-right: 10px;">
        {% endif %}
        <p>Author: <a href="{% url 'articles:articles-author' article.author %}">{{ article.author }}</a></p>
        {% for tag in article.tags.all %}
          <a href="{% url 'articles:articles-tag' tag %}">#{{ tag }}</a>
        {% endfor %}
        <p>Publication date: {{ article.pub_date.date }}</p>
        <form action="{% url 'articles:public-article' article.id %}">
          {% csrf_token %}
          <button class="btn btn-primary" type="submit">Read</button>
        </form>
      {% endfor %}
    </div>
    <div class="pagination" class="container py-5">
      <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
          Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
  </body>
</html>

articles/templates/articles/registration.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>Registration</title>
  </head>
  <body>
    {% load crispy_forms_tags %}
    <div class="container py-5">
      <h1>Register</h1>
      <form action="{% url 'articles:register' %}" method="post">
        {% csrf_token %} 
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Register</button>
        <p class="text-center">
          If you already have an account
          <a href="{% url 'articles:login' %}">Login</a>.
        </p>
      </form>
    </div>
  </body>
</html>